### ISSUE TITLE
Consolidate .Phone and .Windows projects to a Windows 8.1 & Phone 8.1 PCL-targeting project

### ISSUE THREAD

**Issue by bc3tech** [mattleibow/Microsoft-Band-SDK-Bindings#15]
The code is identical, should be usable as such.

**Comment by mattleibow** [comment]
I decided against this PR for a few reasons:
- I want to keep parity with the assemblies from MS
- The `BandClientManager` is not available in the PCL
- Removing the `Phone` project, making the `Windows` project a PCL and then still using a reference to the `netcore451` assemblies is a bit hacky... 
- A NuGet update will then switch to the `portable-win81+wpa81` target, and not `netcore451`
